---
- name: Run Docker build on EC2 instance
  hosts: all
  gather_facts: False
  vars:
    deploy_git_repo: 'github.com/rahilk82/Portfolio.git'
    deploy_git_branch: 'main'

  tasks:
    - name: Change to the directory containing the Dockerfile
      shell: 'cd /home/ubuntu/Portfolio/'

    - name: Clone git repo to latest release
      git:
        repo: "https://{{deploy_git_repo}}"
        dest: '/home/ubuntu/Portfolio/'
        version: "main"
        accept_hostkey: yes


    - name: Stop the Container and Delete
      shell: 'docker stop resume-portfolio && docker rm resume-portfolio'

    - name: Delete the Docker Image
      shell: 'docker rmi portfolio-v2:latest'

    - name: Build New Docker Image
      shell: 'docker build /home/ubuntu/Portfolio -t portfolio-v2'

    - name: Run the docker container
      shell: 'docker run -itd --name resume-portfolio -p 3000:3000 portfolio-v2:latest'
