- name: Java installation
  hosts: ubuntu
  become: true
  tasks:
    - name: Download the JDK binaries
      get_url:
        url: https://download.oracle.com/java/17/archive/jdk-17.0.6_linux-x64_bin.tar.gz
        dest: /opt/jdk-17.0.6_linux-aarch64_bin.tar.gz
    - name: Unzip the downloaded file
      unarchive:
        src: /opt/jdk-17.0.6_linux-aarch64_bin.tar.gz
        dest: /opt
        remote_src: yes
    - name: Set the JAVA_HOME in /etc/profile file
      lineinfile:
        path: /etc/profile
        state: present
        line: "{{ item }}"
      with_items:
        - 'export JAVA_HOME="/opt/jdk-17.0.6"'
        - 'export PATH=$PATH:$JAVA_HOME/bin'
